version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    networks:
      - net

  shopping-api:
    container_name: shopping-api
    build: .
    ports:
      - 4001:4001
    depends_on:
      - db
    networks:
      - net

volumes:
  data: {}

networks:
  net:
    driver: bridge
