version: "3.7"
services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopping
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - net

  shopping-api:
    container_name: shopping-api
    build:
      context: .
    ports:
      - "4001:4001"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: shopping
    volumes:
      - ./src/database/migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

volumes:
  pg_data: {}

networks:
  net:
    driver: bridge
